### ISSUE TITLE
Error: No such option: --timeout

### ISSUE THREAD

**Issue by denysVasylenko** [qwak-ai/deploy-action#1]
**Description:**
I am attempting to utilize the GitHub Action for a batch deployment of a model in my CI pipeline. However, I encountered an issue when executing the command for the build.

Here's the relevant portion of my workflow YAML file:

```
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy Qwak Build
      uses: qwak-ai/deploy-action@v1
      with:
        qwak-api-key: <key>
        model-id:  <model_id>
        build-id: ${{ needs.build.outputs.build_id }}
        deploy-type: batch
        instance: 'small'
        replicas: 2
```
        
**Issue:**
When I run the workflow, the following error is encountered:

```
Printing the Qwak CLI command for debug purposes:
qwak models deploy batch --model-id <model_id> --instance small --replicas 10 --timeout 30

Command Output:



An error occurred while running the `qwak models deploy` command.
 Usage: qwak models deploy batch [OPTIONS]
Try 'qwak models deploy batch --help' for help.

Error: No such option: --timeout
```

**Assumption:**
Based on the error message, it appears that there is an issue with the --timeout option.

**Request for Assistance:**
Could someone please provide guidance on how to resolve this issue with the --timeout option? Thank you!
